version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - ${RAILWAY_DYNAMIC_PORT:-5000}:5000
    env_file: 
      - .env
    networks:
      - mynetwork
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - ${RAILWAY_STATIC_PORT:-3000}:3000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
